# Nome do pipeline
name: Pipeline de CI/CD para React App

# Gatilho: Roda em push na branch main
on:
  push:
    branches: [ "main" ]

# Tarefas (Jobs)
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configurar o Node.js
      - name: Configurar Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Instalar as dependências
      - name: Instalar dependências
        run: npm ci

      # 4. Testes
      - name: Rodar os testes
        run: echo "Nenhum teste configurado, pulando esta etapa."

      # 5. Construir a aplicação (gera a pasta 'build' ou 'dist')
      - name: Build do projeto React
        run: npm run build

      # 6. Salvar o artefato de build para usar no job de deploy
      - name: Salvar o artefato de build
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist 

#  Job para fazer o deploy no GitHub Pages
#  deploy:
#    needs: build-and-test
#    permissions:
#      pages: write
#      id-token: write
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    runs-on: ubuntu-latest
#    steps:
#      - name: Baixar artefato de build
#        uses: actions/download-artifact@v4
#        with:
#          name: build-files
#          path: .
#      - name: Configurar Pages
#        uses: actions/configure-pages@v5
#      - name: Upload para Pages
#        uses: actions/upload-pages-artifact@v3
#        with:
#          path: '.'
#      - name: Fazer Deploy no GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v4